---
services:
  - docker

before_install:
  - docker build -t zulhilmizainuddin/protobufjs-docker .

script:
  - docker run --rm -v $(pwd)/proto:/var/proto protobufjs-docker -t static-module -o compiled.js addressbook.proto
