---
services:
  - docker

before_install:
  - docker build -t zulhilmizainuddin/protobufjs-docker .

script:
  - docker run --rm -v $(pwd)/proto:/usr/src/proto zulhilmizainuddin/protobufjs-docker -t static-module -w commonjs -o addressbook.js addressbook.proto
  - ls -la ./proto/addressbook.js