---
services:
  - docker

before_install:
  - docker build -t zulhilmizainuddin/protobufjs-docker .

script:
  - docker run --rm -v $(pwd)/proto:/var/proto zulhilmizainuddin/protobufjs-docker -t static-module -o addressbook.js addressbook.proto
  - ls -la
  - ls -la proto
  # - test -f $(pwd)/proto/adressbook.js