---
services:
  - docker

before_install:
  - docker build -t zulhilmizainuddin/protobufjs-docker .

script:
  - docker run --rm -v $(pwd)/proto:/var/proto zulhilmizainuddin/protobufjs-docker -t static-module -o addressbook.js addressbook.proto
  - test -f ./proto/adressbook.js