---
services:
  - docker

before_install:
  - docker build -t zulhilmizainuddin/protobufjs-docker .

script:
  - docker run --rm -v $(pwd)/proto:/usr/src/proto zulhilmizainuddin/protobufjs-docker pbjs -t static-module -w commonjs -o addressbook.js addressbook.proto
  - ls -la ./proto/addressbook.js
  - docker run --rm -v $(pwd)/proto:/usr/src/proto zulhilmizainuddin/protobufjs-docker pbts -o addressbook.d.ts addressbook.js
  - ls -la ./proto/addressbook.d.ts
  